### ISSUE TITLE
Enhancement: Dual y-axes labels for TWTT and Depth

### ISSUE THREAD

**Issue by dshean** [dlilien/ImpDAR#13]
I think most of the visualization options require the user to select one or the other for the left axis.  Would be good to have a third option to show both.  Complications for nonlinear scaling due to variable velocity profile, but I think it should still be possible.

**Comment by dlilien** [comment]
Yeah, this should be easy and useful. I'll probably just linearize/fudge the secondary axis for the variable velocity.

**Comment by dshean** [comment]
Awesome!  Thanks for adding this feature @dlilien!  Will give it a try soon.
