### ISSUE TITLE
Memory usage reduction for conversion, raw load, and processing.

### ISSUE THREAD

**Issue by dlilien** [dlilien/ImpDAR#17]
We allow users to process multiple files simultaneously, and at present we load all simultaneously. In almost all cases, this unnecessarily uses extra memory. Probably worth addressing simultaneously with #16 since they are interrelated. 

Only exception I can think of is Gecko load. Any other exceptions, @benhills ?

If not, I think we can switch load_and_exit, process, and convert to operate sequentially over the files rather than load all, do any processing to all, then save all, and thus limit memory to a single file.

**Comment by benhills** [comment]
As you realized, the OSU custom system was the other exception. Those are the only two that I could think of.
