### ISSUE TITLE
Adaptive Horizontal Filter

### ISSUE THREAD

**Issue by benhills** [dlilien/ImpDAR#20]
This filter uses a piecewise scaling function to insure that the filter only affects the top layers of data. As it is now, the scaling function is the sum of a parabola (near the surface) and a Gaussian (below the surface). It is a bit confusing to me why it is written this way, and when I tried to use it I was surprised at how much this filter is changing the image below ~100 m.

I am thinking of changing to a tanh function with depth. Before I make any changes though, I wanted to make sure that this is leftover from stodeep and that is why it is currently confusing. @dlilien if you wrote it this way on purpose please let me know.

**Comment by dlilien** [comment]
I didn't do this on purpose. It is also possible that I butchered the port from StoDeep on this one, I remember being quite confused as to why it was working the way it was.

**Comment by benhills** [comment]
Haha, I figured it wasn't you. Nick is under the impression that the St. Olaf undergrads intentionally made things more confusing than they needed to be as some sort of gate-keeping. In this case, it is possible that whoever wrote it just couldn't figure out a simpler way to do it. I can rewrite this function.

**Comment by benhills** [comment]
I addressed this, but the changes are mixed in with my changes to the auto picker on #19. I don't see an urgent need to separate the two, so I will just let this sit with that pull request.
