### ISSUE TITLE
Kirchhoff migration giving 0's when using C code

### ISSUE THREAD

**Issue by benhills** [dlilien/ImpDAR#33]
This came up in a conversation with Emma Erwin. It seems that the Kirchhoff migration in the jupyter notebook tutorial is outputting a full array of 0's. The python version still works.

I am happy to fix this, and there are some other small migration changes that I want to make, so I will submit a PR at some point soon hopefully.

**Comment by dlilien** [comment]
Yeah, it would be great if you can take a look at this. I almost always use sumigtk, so had not noticed this.

**Comment by benhills** [comment]
Initial solution is here

https://github.com/benhills/ImpDAR/tree/kirchhoff

I am going to wait to submit the PR because there are still some other changes that I want to think about and I hate getting all the emails from codecov ever time stuff fails.

**Comment by dlilien** [comment]
This is fixed in the merging of #39. Sorry for taking so long on it.
