### ISSUE TITLE
Picker cannot 'select' a line

### ISSUE THREAD

**Issue by benhills** [dlilien/ImpDAR#34]
I am having trouble selecting previously picked lines after a recent update. 

I made this change in the /impdar/bin/pickgui.py and it seems to have fixed. I can make a PR later but I want to do the picking that I need to do to be sure that no other issues come up.

diff --git a/impdar/gui/pickgui.py b/impdar/gui/pickgui.py
index 517a201..f66ebe8 100644
--- a/impdar/gui/pickgui.py
+++ b/impdar/gui/pickgui.py
@@ -251,9 +251,9 @@ class InteractivePicker(QtWidgets.QMainWindow, RawPickGUI.Ui_MainWindow):
             self.bpid = self.fig.canvas.mpl_connect('button_press_event', self._click)
             for center, bottom, top in zip(self.cline, self.bline, self.tline):
                 if center is not None:
-                    center.set_pickradius(0)
-                    bottom.set_pickradius(0)
-                    top.set_pickradius(0)
+                    center.set_picker(0)
+                    bottom.set_picker(0)
+                    top.set_picker(0)
         else:
             self.modeButton.setText(_translate('MainWindow', 'Select Mode'))
             self.FigCanvasWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
@@ -262,9 +262,9 @@ class InteractivePicker(QtWidgets.QMainWindow, RawPickGUI.Ui_MainWindow):
             self.bpid = self.fig.canvas.mpl_connect('pick_event', self._click)
             for center, bottom, top in zip(self.cline, self.bline, self.tline):
                 if center is not None:
-                    center.set_pickradius(5)
-                    bottom.set_pickradius(5)
-                    top.set_pickradius(5)
+                    center.set_picker(5)
+                    bottom.set_picker(5)
+                    top.set_picker(5)

     def _update_color_reversal(self, state):
         if state == QtCore.Qt.Checked:

**Comment by dlilien** [comment]
This should be fixed in #43, so I'm closing.
