### ISSUE TITLE
Problem loading segy file

### ISSUE THREAD

**Issue by anna7br** [dlilien/ImpDAR#36]
Hi! I am super happy with ImpDAR! So far, I had no problems, however, my segy files (exported from UgCS' GPR) cause troubles: I cannot load these files. Any ideas why this does not work or how I could solve it?

I was using the code from one of the tutorials:

```
# To look through data files we use glob which is a library
# that finds all the file names matching our description
import glob

# Impdar's loading function
from impdar.lib import load
dat = load.load('segy','data/2022-12-21-11-19-07-gpr.sgy')


# save the loaded data as a .mat file
dat.save('test_data_raw.mat')

# Impdar's plotting function
from impdar.lib.plot import plot_traces, plot_radargram
# %matplotlib inline
plot_radargram(dat)
```

The file I used is attached. Would be awesome to receive some help! 
[2022-12-21-11-19-07-gpr.sgy.zip](https://github.com/dlilien/ImpDAR/files/10296991/2022-12-21-11-19-07-gpr.sgy.zip)

This is the error message I get:
```
Unknown Record Mode
Unknown in Trigger Source
Unknown Trigger Slope
Unknown External Trigger Coupling
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?705227a7-3c45-425b-ae42-784ced775056)
```
(The size, however, should not be the problem here.)

**Comment by anna7br** [comment]
Meanwhile I managed to make it work :)
The problem was related to the segyio package that ImpDAR uses under the hood to import the data. So I had to adapt the import function in [load_segy.py](impdar/lib/load/load_segy.py) to:
f = segyio.open(fn_sgy, ignore_geometry=True, endian='little')

Just posting this here in case you want to make this adaptation as well to allow more flexibility when it comes to importing SEG-Y data.

**Comment by benhills** [comment]
Hi Anna,

I am just seeing this, sorry nobody responded, happy you are finding impdar useful!

I would be happy to walk you through a pull request for this change if you want to make one, that way your contributions can be added to the repository. 

- Ben

**Comment by anna7br** [comment]
Hi Ben,
Thanks for getting back to me!
I am happy to submit a pull request. Please just let me know how to proceed.
- Anna

**Comment by benhills** [comment]
Great, it depends how familiar you are with git.

If you haven't used git much before and the change is small (seems like it is) I would just use the web interface to edit the file and then it will walk you through how to commit the changes. So go directly to the file:
https://github.com/dlilien/ImpDAR/blob/main/impdar/lib/load/load_segy.py
press the edit button in the top right corner and then when you try to save it will ask whether you want to commit on the main branch or on a separate branch and open a pull request. You wouldn't be allowed to commit on the main branch, so go with the pull request option. Link to this issue in the pull request if you can :)

If you are more familiar with this, I would fork the repository and do this on your own fork then do a PR from there. Especially if you are going to keep using and developing on impdar it is easier to have your own version of the repository.

**Comment by anna7br** [comment]
As far as I can tell, it should have worked :)

**Comment by benhills** [comment]
Nice thanks
